services:
  flask:
    container_name: restaurant_container
    restart: on-failure
    tty: true
    image: restaurant_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
